### ISSUE TITLE
[BUG] Crash on dying/save load

### ISSUE THREAD

**Issue by Geborgen** [Geborgen/nordic-souls#60]
**Describe The Bug**
When player dies or reloads save, game crashes. Happens especially when player dies in different cell compared to where previous save is.

**List Version**
2.3.2 was supposed to fix, but is still an issue in this version.

**Comment by Bino52** [comment]
Using a crash log '' Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FFD1B91AB23 BeardMaskFix.dll+000AB23 Hooks::Biped::DismemberBeard '' 
Something wrong with this Beard Mask Fix ..

**Comment by Bino52** [comment]
I removed both, but them i had a problem with the head of my character..

**Comment by Geborgen** [comment]
Should be finally fixed in v2.3.3

**Comment by TazerReloaded** [comment]
Unfortunately I still get a CTD on every load from a running game. Save file is new (v2.3.3).
I found that disabling the .NET Script Framework resolves this issue, though I'm not sure if that kills other mods.
The author emphasizes that it is not compatible with patch 1.6 or later: https://www.nexusmods.com/skyrimspecialedition/mods/21294

I also uploaded my recent crash dumps from said framework:
[Crash_2024_2_28_22-12-39.txt](https://github.com/Geborgen/nordic-souls/files/14444502/Crash_2024_2_28_22-12-39.txt)
[Crash_2024_2_28_23-40-25.txt](https://github.com/Geborgen/nordic-souls/files/14444503/Crash_2024_2_28_23-40-25.txt)
[Crash_2024_2_29_0-3-9.txt](https://github.com/Geborgen/nordic-souls/files/14444504/Crash_2024_2_29_0-3-9.txt)
[Crash_2024_2_29_0-18-26.txt](https://github.com/Geborgen/nordic-souls/files/14444505/Crash_2024_2_29_0-18-26.txt)
[Crash_2024_2_29_1-26-50.txt](https://github.com/Geborgen/nordic-souls/files/14444506/Crash_2024_2_29_1-26-50.txt)

I hope that helps, I tried almost all lists out there and yours is my favourite!

**Comment by TazerReloaded** [comment]
I updated to 2.3.3.1 yesterday, and the crashes are completely gone!
I had occasional freezes in outside areas with 2.3.3 (had to kill the game with task manager), these are also gone.
I migrated my save with ReSaver, which worked very well, I have not found any bugs that could indicate save corruption. Checked with ReSaver again after some hours of gameplay today, everything still clean.

Thank you for your efforts!
